version: '3.9'

services:
  landing:
    build: # откуда брать инструкции для билда
      context: ./app/
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: landing # название образа
    container_name: landing # имя контейнера
    restart: unless-stopped # перезагрузка, если что-то пошло не так
    stdin_open: true
    tty: true
    volumes:
      - ./app:/home/app
    ports:
      - "3333:3333" # какой порт показывать снаружи