version: '3.9'

services:
  landing:
    build:
      context: ./app/
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${UID}
        PORT: ${DEV_PORT}
    image: ${PROJECT_NAME}_image
    container_name: ${PROJECT_NAME}_landing
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./app:/home/app
    ports:
      - "${DEV_PORT}:3333"