apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kommunity-landing
  namespace: kommunity
  labels:
    app: kommunity-landing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: community42.ru
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kommunity-landing
            port: 
              number: 80
  tls:
  - hosts:
    - community42.ru
    secretName: kommunity-landing-ssl