on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and push artifact to registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7
      - name: Build and push
        uses: aevea/action-kaniko@master
        with:
          image: arsolitt/kommunity-landing
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ steps.short-sha.outputs.sha }}
          tag_with_latest: true
  deploy:
    needs: build
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: "apply -f .kubernetes -n kommunity"
            