on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy static
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install deps
        run: cd app && npm ci
      - name: Production build
        run: cd app && npm run build
      - name: Upload to hosting1
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.HOST }}
          remote-user: ${{ secrets.SSH_LOGIN }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          source-path: ./dist/*
          destination-path: /var/www/kommunityLanding/
          rsync-options: --dry-run